
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 05 15:00:25 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int EGALITE = 24;
  public static final int IDF = 31;
  public static final int EGAL = 8;
  public static final int CSTENTIERE = 32;
  public static final int OU = 29;
  public static final int PLUS = 18;
  public static final int LIRE = 9;
  public static final int INFERIEUR = 25;
  public static final int ECRIRE = 7;
  public static final int DIVISION = 21;
  public static final int FONCTION = 5;
  public static final int TANTQUE = 11;
  public static final int ALORS = 15;
  public static final int SUPERIEUR = 26;
  public static final int REPETER = 12;
  public static final int NON = 30;
  public static final int PARFER = 23;
  public static final int MOINS = 19;
  public static final int POINTVIRGULE = 6;
  public static final int FINTANTQUE = 13;
  public static final int SINON = 16;
  public static final int DIFFERENCE = 27;
  public static final int TYPE = 33;
  public static final int PAROUVR = 22;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 20;
  public static final int ET = 28;
  public static final int SI = 14;
  public static final int error = 1;
  public static final int RETOUR = 10;
  public static final int DEBUT = 3;
  public static final int FINSI = 17;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

