
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 01 20:40:12 CEST 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 5;
  public static final int TANTQUE = 14;
  public static final int CROFER = 28;
  public static final int EGAL = 10;
  public static final int REPETER = 15;
  public static final int SI = 17;
  public static final int RETOUR = 12;
  public static final int VIRGULE = 7;
  public static final int FIN = 4;
  public static final int LIRE = 11;
  public static final int LONGUEUR = 13;
  public static final int OU = 34;
  public static final int TYPE = 38;
  public static final int NON = 35;
  public static final int PLUS = 21;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOINS = 22;
  public static final int ET = 33;
  public static final int IDF = 36;
  public static final int SINON = 19;
  public static final int ALORS = 18;
  public static final int EGALITE = 29;
  public static final int PARFER = 26;
  public static final int POINT = 8;
  public static final int DIFFERENCE = 32;
  public static final int CSTENTIERE = 37;
  public static final int SUPERIEUR = 31;
  public static final int CROUVR = 27;
  public static final int PROGRAMME = 2;
  public static final int FINTANTQUE = 16;
  public static final int POINTVIRGULE = 6;
  public static final int INFERIEUR = 30;
  public static final int FINSI = 20;
  public static final int DIVISION = 24;
  public static final int PAROUVR = 25;
  public static final int MULTIPLICATION = 23;
  public static final int ECRIRE = 9;
}

