
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 12 13:48:24 CET 2019
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int EGALITE = 22;
  public static final int IDF = 29;
  public static final int EGAL = 7;
  public static final int CSTENTIERE = 30;
  public static final int OU = 27;
  public static final int PLUS = 16;
  public static final int LIRE = 8;
  public static final int INFERIEUR = 23;
  public static final int ECRIRE = 6;
  public static final int DIVISION = 19;
  public static final int TANTQUE = 9;
  public static final int ALORS = 13;
  public static final int SUPERIEUR = 24;
  public static final int REPETER = 10;
  public static final int NON = 28;
  public static final int PARFER = 21;
  public static final int MOINS = 17;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 11;
  public static final int SINON = 14;
  public static final int DIFFERENCE = 25;
  public static final int TYPE = 31;
  public static final int PAROUVR = 20;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 18;
  public static final int ET = 26;
  public static final int SI = 12;
  public static final int error = 1;
  public static final int DEBUT = 3;
  public static final int FINSI = 15;
  public static final int FIN = 4;
  public static final int PROGRAMME = 2;
}

